// Command gendocs regenerates docs/LAYERS.generated.md from the nn
// package's exported constructor functions (a function returning a single
// "*Xxx" layer/module pointer) and their doc comments — an always-
// up-to-date reference that can't silently drift from the code the way a
// hand-maintained table can, complementing (not replacing) the
// hand-curated prose and examples in docs/GUIDE.md.
//
// Run via `go generate ./...` (see the //go:generate directive in
// nn/doc.go) or directly: `go run ./cmd/gendocs` from the repo root.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/doc"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	srcDirName  = "nn"
	outPathName = "docs/LAYERS.generated.md"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

// findModuleRoot walks up from the current directory looking for go.mod,
// so this command works the same whether it's invoked as `go run
// ./cmd/gendocs` from the repo root or via `go generate` (which runs with
// cwd set to the directory holding the //go:generate directive, e.g. nn/).
func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found in %s or any parent directory", dir)
		}
		dir = parent
	}
}

type constructorEntry struct {
	Name string
	Sig  string
	Doc  string
}

// starPointerResultTypeName returns "TypeName" when results is exactly
// one "*TypeName" return value, or "" otherwise (named return, multiple
// returns, non-pointer, ...) — the same "looks like a constructor"
// heuristic nn/convention_test.go uses to find Module-shaped types.
func starPointerResultTypeName(results *ast.FieldList) string {
	if results == nil || len(results.List) != 1 || len(results.List[0].Names) > 1 {
		return ""
	}
	star, ok := results.List[0].Type.(*ast.StarExpr)
	if !ok {
		return ""
	}
	ident, ok := star.X.(*ast.Ident)
	if !ok {
		return ""
	}
	return ident.Name
}

func run() error {
	root, err := findModuleRoot()
	if err != nil {
		return err
	}
	srcDir := filepath.Join(root, srcDirName)
	outPath := filepath.Join(root, outPathName)

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, srcDir, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parsing %s: %w", srcDir, err)
	}
	pkgAST, ok := pkgs["nn"]
	if !ok {
		return fmt.Errorf("no package \"nn\" found in ./%s", srcDir)
	}

	// Drop _test.go files before handing the tree to go/doc, so test-only
	// helpers never leak into the generated reference.
	files := map[string]*ast.File{}
	for name, f := range pkgAST.Files {
		if !strings.HasSuffix(name, "_test.go") {
			files[name] = f
		}
	}
	pkgAST.Files = files

	docPkg := doc.New(pkgAST, "github.com/stolzmi/neugo/nn", doc.AllDecls)

	// go/doc groups a "func NewFoo() *Foo"-shaped function under Foo's own
	// Type.Funcs (its documented "constructor"), not in the flat
	// package-level Package.Funcs list — so every layer constructor
	// (ReLU, Linear, Conv2D, ...) lives under some Types[i].Funcs, and
	// Package.Funcs only holds genuinely standalone functions (NewRNG,
	// ParamCount, ...). Both lists have to be scanned to find every
	// constructor-shaped function in the package.
	var allFuncs []*doc.Func
	allFuncs = append(allFuncs, docPkg.Funcs...)
	for _, typ := range docPkg.Types {
		allFuncs = append(allFuncs, typ.Funcs...)
	}

	var entries []constructorEntry
	for _, fn := range allFuncs {
		if starPointerResultTypeName(fn.Decl.Type.Results) == "" {
			continue
		}
		var buf bytes.Buffer
		if err := format.Node(&buf, fset, fn.Decl.Type); err != nil {
			return fmt.Errorf("formatting signature of %s: %w", fn.Name, err)
		}
		sig := fn.Name + strings.TrimPrefix(buf.String(), "func")
		entries = append(entries, constructorEntry{Name: fn.Name, Sig: sig, Doc: strings.TrimSpace(fn.Doc)})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })

	var out strings.Builder
	out.WriteString("<!-- Generated by `go generate` (cmd/gendocs) from nn's exported constructors — do not edit by hand. -->\n\n")
	out.WriteString("# NeuGo layer constructor reference\n\n")
	out.WriteString("Every exported `nn` package constructor (a function returning a single `*Xxx` layer/module pointer), auto-extracted from source so this list can't silently drift from the code. For prose, design rationale, and worked examples, see [`GUIDE.md`](GUIDE.md).\n\n")
	for _, e := range entries {
		fmt.Fprintf(&out, "## `%s`\n\n```go\n%s\n```\n\n", e.Name, e.Sig)
		if e.Doc != "" {
			out.WriteString(e.Doc)
			out.WriteString("\n\n")
		}
	}

	if err := os.WriteFile(outPath, []byte(out.String()), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d constructors)\n", outPath, len(entries))
	return nil
}
