// Code generated by neugo export. DO NOT EDIT.
package model

import "math"

var w0 = []float32{-0x1.3bd794p+00, 0x1.fe566p+00, -0x1.fe68c8p+01, -0x1.2aadb8p+01, 0x1.38263p+01, 0x1.f75bdp+00, 0x1.cfb3c6p+00, 0x1.b37a32p+01, -0x1.766abap-01, 0x1.fe64ccp+00, 0x1.fe7b1ap+01, -0x1.2d0dccp-02, 0x1.78bfb2p+01, 0x1.f75962p+00, 0x1.cfb414p+00, -0x1.b37a8p+01}
var b0 = []float32{0x0p+00, -0x1.fe57cap+00, -0x1.efd2c4p-12, 0x1.236c7p+02, -0x1.fabaf4p-19, -0x1.f75758p+00, -0x1.cfb368p+00, -0x1.a4ad4ep-17}
var w1 = []float32{-0x1.d6a1ap-02, -0x1.bb5f1ap+01, 0x1.a7686cp+01, -0x1.b9322ep+00, 0x1.77a8f6p+01, -0x1.dbecacp+01, -0x1.c822d2p+01, 0x1.9dc65ap+01}
var b1 = []float32{-0x1.929b42p+01}

// Predict runs inference. len(input) must be 2;
// returns 1 values.
func Predict(input []float32) []float32 {
	cur := input
	cur = nnLinear(cur, w0, b0, 2, 8)
	nnReLU(cur)
	cur = nnLinear(cur, w1, b1, 8, 1)
	nnSigmoid(cur)
	return cur
}

func nnLinear(x, w, b []float32, in, out int) []float32 {
	result := make([]float32, out)
	for o := 0; o < out; o++ {
		sum := b[o]
		for i := 0; i < in; i++ {
			sum += x[i] * w[i*out+o]
		}
		result[o] = sum
	}
	return result
}

func nnReLU(x []float32) {
	for i := range x {
		if x[i] > 0 {
			// positive: keep value
		} else {
			x[i] = 0
		}
	}
}

func nnSigmoid(x []float32) {
	for i := range x {
		x[i] = float32(1 / (1 + math.Exp(float64(-x[i]))))
	}
}
